FROM mcr.microsoft.com/devcontainers/ruby:0-3
COPY ./setup.sh /opt/src/scripts/setup.sh
# CMD apt-get update
# RUN apt-get install software-properties-common
# RUN apt-add-repository -y ppa:rael-gc/rvm
# RUN apt-get update
# RUN apt-get install -y rvm
# CMD rvm install 2.7.4
# CMD rvm use 2.7.4 --default